In [3]:
import pandas as pd

In [4]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')b

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [5]:
df.head

NameError: name 'df' is not defined

In [6]:
df.head()

NameError: name 'df' is not defined

In [7]:
pd.__version__

'2.3.1'

In [8]:
df['model_year'].unique()

NameError: name 'df' is not defined

In [13]:
df['fuel_type'].unique()

KeyError: 'fuel_type'

In [14]:
print(df.columns)

Index(['model_year'], dtype='object')


In [15]:
# check all column names
print(df.columns)

# count unique fuel types
print("Number of fuel types:", df['fuel_type'].nunique())

# list the unique fuel types
print("\nUnique fuel types:", df['fuel_type'].unique())

# count rows per fuel type
print("\nCounts per fuel type:\n", df['fuel_type'].value_counts())


Index(['model_year'], dtype='object')


KeyError: 'fuel_type'

In [16]:
print(df.columns.tolist())

['model_year']


In [26]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)

In [1]:
num_missing_cols = (df.isnull().sum() > 0).sum()


NameError: name 'df' is not defined

In [2]:
print(df.columns.tolist())

NameError: name 'df' is not defined

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)

In [4]:
print(df.shape)        # rows, columns
print(df.columns.tolist())  # list of column names

(9704, 11)
['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'fuel_efficiency_mpg']


In [5]:
num_missing_cols = (df.isnull().sum() > 0).sum()
print("Number of columns with missing values:", num_missing_cols)

Number of columns with missing values: 4


In [6]:
df.head(100)


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0         NaN     2542.392402   
4                   210            1.0       140.0     3460.870990   
..                  ...            ...         ...             ...   
95                  200            2.0       232.0     3476.591797   
96                  120            5.0       172.0     3475.004528   
97                  280            2.0       133.0     3398.340992   
98                  250            NaN       109.0     3210.919484   
99                  240            5.0       194.0     3019.882237   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
..           ...         ...     ...       ...                ...        ...   
95          11.0        2016     USA  Gasoline    All-wheel drive        1.0   
96          13.8        2013     USA    Diesel    All-wheel drive        NaN   
97          15.3        2015  Europe    Diesel    All-wheel drive        1.0   
98          14.6        2021     USA    Diesel    All-wheel drive        0.0   
99          17.5        2017     USA  Gasoline    All-wheel drive        1.0   

    fuel_efficiency_mpg  
0             13.231729  
1             13.688217  
2             14.246341  
3             16.912736  
4             12.488369  
..                  ...  
95            14.674507  
96            12.743224  
97            13.930128  
98            13.128946  
99            14.882406  

[100 rows x 11 columns]

In [7]:
df.head(500)


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    170            3.0       159.0     3413.433759   
1                    130            5.0        97.0     3149.664934   
2                    170            NaN        78.0     3079.038997   
3                    220            4.0         NaN     2542.392402   
4                    210            1.0       140.0     3460.870990   
..                   ...            ...         ...             ...   
495                  260            2.0       174.0     2702.257301   
496                  210            4.0       149.0     2361.085388   
497                  160            7.0       157.0     3216.103540   
498                  160            3.0       195.0     2583.200028   
499                  260            8.0       158.0     3111.763126   

     acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0            17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1            17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2            15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3            20.2        2009     USA    Diesel    All-wheel drive        2.0   
4            14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
..            ...         ...     ...       ...                ...        ...   
495          18.4        2011  Europe  Gasoline    All-wheel drive        2.0   
496          12.2        2020  Europe  Gasoline  Front-wheel drive        NaN   
497          16.3        2017     USA  Gasoline    All-wheel drive       -1.0   
498          14.2        2014  Europe    Diesel  Front-wheel drive        0.0   
499          10.3        2009  Europe  Gasoline  Front-wheel drive        2.0   

     fuel_efficiency_mpg  
0              13.231729  
1              13.688217  
2              14.246341  
3              16.912736  
4              12.488369  
..                   ...  
495            16.068975  
496            18.799465  
497            14.199962  
498            17.633442  
499            15.271080  

[500 rows x 11 columns]

In [8]:
max_efficiency_asia = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

print("Maximum fuel efficiency of cars from Asia:", max_efficiency_asia)

Maximum fuel efficiency of cars from Asia: 23.759122836520497


In [9]:
median_horsepower = df['horsepower'].median()


In [10]:
median_horsepower = df['horsepower'].median()

In [11]:
max_horsepower = df['horsepower'].max()

In [12]:
df median_horsepower = df['horsepower'].median()

SyntaxError: invalid syntax (608844512.py, line 1)

In [13]:
median_horsepower = df['horsepower'].median()

In [14]:
median_horsepower = df['horsepower'].median()
print("Median horsepower:", median_horsepower)

Median horsepower: 149.0


In [15]:
most_frequent_horsepower = df['horsepower'].mode()[0]
print("Most frequent horsepower:", most_frequent_horsepower)


Most frequent horsepower: 152.0


In [16]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

NameError: name 'most_frequent_hp' is not defined

In [17]:
['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

SyntaxError: cannot assign to literal (3960833234.py, line 1)

In [18]:
# Step 1: calculate the most frequent horsepower value
most_frequent_hp = df['horsepower'].mode()[0]

In [ ]:
# Step 1: calculate the most frequent horsepower value
most_frequent_hp = df['horsepower'].mode()[0]
print("Most frequent horsepower:", most_frequent_hp)


Most frequent horsepower: 152.0


In [20]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [21]:
# Step 1: calculate the most frequent horsepower value
most_frequent_hp = df['horsepower'].mode()[0]
print("Most frequent horsepower:", most_frequent_hp)

Most frequent horsepower: 152.0


In [22]:
# Step 1: calculate the most frequent horsepower value
most_frequent_hp = df['horsepower'].mode()[0]
print("Most frequent horsepower:", most_frequent_hp)
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

Most frequent horsepower: 152.0


In [23]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)
print("Missing horsepower values:", df['horsepower'].isnull().sum())

Missing horsepower values: 0


In [24]:
median_horsepower = df['horsepower'].median()
print("Median horsepower:", median_horsepower)

Median horsepower: 152.0


In [25]:
asia_cars = df[df['origin'] == 'Asia']


In [26]:
asia_cars = df[df['origin'] == 'Asia']
print("Number of cars from Asia:", asia_cars.shape[0])

Number of cars from Asia: 3247


In [27]:
asia_cars = df[df['origin'] == 'Asia']
print("Number of cars from Asia:", asia_cars.shape[0])
asia_cars.shape[0]      # number of rows                


Number of cars from Asia: 3247


3247

In [28]:
vehicle_count = df.shape[0], model_year_count = df['model_year'].nunique()
model_year_count = df['model_year'].nunique()

TypeError: cannot unpack non-iterable int object

In [29]:
asia_subset = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
asia_subset.head()

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [30]:
asia_two = asia[['vehicle_weight', 'model_year']]


NameError: name 'asia' is not defined

In [31]:
asia_two = asia[['vehicle_weight', 'model_year']]
asia_two = asia[['vehicle_weight', 'model_year']]
asia_two.head()

NameError: name 'asia' is not defined

In [32]:
asia_cars == asia[['vehicle_weight', 'model_year']]

NameError: name 'asia' is not defined

In [33]:
asia_7 = asia_two.head(7)

NameError: name 'asia_two' is not defined

In [34]:
asia_subset = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
asia_subset.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [40]:
X = df.loc[[8, 12, 14, 20, 21, 34, 38], ['vehicle_weight', 'model_year']].to_numpy()
print(X.shape)  # (7, 2)
print(X)

(7, 2)
[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]


In [41]:
XTX = X.T @ X           # matrix-matrix multiplication
print(XTX)
print(XTX.shape)        # should be (2, 2)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]
(2, 2)


In [42]:
XTX_inv = np.linalg.inv(XTX)

NameError: name 'np' is not defined

In [43]:
XTX_inv_df = pd.DataFrame(
    np.linalg.inv(XTX_df.to_numpy()),
    index=XTX_df.index,
    columns=XTX_df.columns

SyntaxError: incomplete input (774174383.py, line 4)

In [44]:
ond = np.linalg.cond(XTX)
det = np.linalg.det(XTX)
print("det(XTX):", det)
print("cond(XTX):", cond)

NameError: name 'np' is not defined

In [45]:
import numpy as np

# optional: check determinant / condition number
print("det(XTX):", np.linalg.det(XTX))
print("cond(XTX):", np.linalg.cond(XTX))

# try the regular inverse; fall back to pseudoinverse if singular
try:
    XTX_inv = np.linalg.inv(XTX)
except np.linalg.LinAlgError:
    XTX_inv = np.linalg.pinv(XTX)   # robust fallback

print("XTX_inv:\n", XTX_inv)

# verify: XTX_inv should be (approximately) the inverse
print("Close to identity?",
      np.allclose(XTX @ XTX_inv, np.eye(XTX.shape[0]), atol=1e-8))

det(XTX): 49647390896215.67
cond(XTX): 163.40615128004052
XTX_inv:
 [[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]
Close to identity? True


In [46]:
import numpy as np

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200], dtype=np.float64)
print(y.shape)   # (7,)
print(y)         # sanity check


(7,)
[1100. 1300.  800.  900. 1000. 1100. 1200.]


In [47]:
w = XTX_inv @ X.T @ y
w_sum = w.sum()
w, w_sum

(array([0.01386421, 0.5049067 ]), np.float64(0.5187709081074016))